import { Inter } from "next/font/google";
import "./globals.css";
import WeployScript from "./weploy-script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head><WeployScript /></head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
